export const ADD_QUESTION_BIRD = 'APP/ADD_QUESTION_BIRD';
export const CHOSEN_CORRECT_BIRD = 'APP/CHOSEN_CORRECT_BIRD';

export const PAGE_INCREMENT = 'APP/PAGE_INCREMENT';
export const PAGE_RESTART = 'APP/PAGE_RESTART';

export const APP_CHOSE_BIRD = 'APP/CHOSE_BIRD';
export const APP_ROUND_INCREMENT = 'APP/ROUND_INCREMENT';
export const APP_ROUND_REMOVE = 'APP/ROUND_REMOVE';
export const APP_ADD_SCORE = 'APP/ADD_SCORE';
export const APP_ADD_ATTEMPTS = 'APP/ADD_ATTEMPTS';
export const APP_REMOVE_SCORE = 'APP/REMOVE_SCORE';
export const APP_REMOVE_ATTEMPTS = 'APP/REMOVE_ATTEMPTS';
export const APP_CORRECT_ANSWER = 'APP/CORRECT_ANSWER';
export const APP_INCORRECT_ANSWER = 'APP/INCORRECT_ANSWER';
export const APP_REMOVE_ANSWERS ='APP/REMOVE_ANSWER';


export const GAME_STOP = 'APP/GAME_STOP';
export const GAME_START = 'APP/GAME_START';